name: flutter_shaders_example
description: play with shaders in flutter
version: 1.1.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: 3.19.2

dependencies:
  flutter:
    sdk: flutter
  flutter_shaders: ^0.1.3
  photo_view: ^0.15.0
  rive: ^0.11.17
  sensors_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  theodo_analysis: ^1.4.0

flutter:
  uses-material-design: true
  generate: true
  shaders:
    - shaders/ripple.frag
    - shaders/gradient.frag
    - shaders/water_ripple.frag
    - shaders/dir_glow.glsl
    - shaders/halo.frag
    - shaders/stripes_pattern.frag
  assets:
    - assets/
